# Generated by Django 5.1.5 on 2025-03-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('hostname', models.CharField(max_length=255)),
                ('system', models.CharField(max_length=50)),
                ('version', models.TextField()),
                ('release', models.CharField(max_length=100)),
                ('machine', models.CharField(max_length=50)),
                ('processor', models.CharField(max_length=255)),
                ('architecture', models.CharField(max_length=50)),
                ('physical_cores', models.IntegerField()),
                ('total_cores', models.IntegerField()),
                ('max_frequency', models.FloatField()),
                ('min_frequency', models.FloatField()),
                ('current_frequency', models.FloatField()),
                ('cpu_usage', models.FloatField()),
                ('total_memory', models.FloatField()),
                ('available_memory', models.FloatField()),
                ('used_memory', models.FloatField()),
                ('memory_usage', models.FloatField()),
                ('total_disk_space', models.FloatField()),
                ('used_disk_space', models.FloatField()),
                ('free_disk_space', models.FloatField()),
                ('disk_usage', models.FloatField()),
                ('ip_address', models.GenericIPAddressField()),
                ('bytes_sent', models.BigIntegerField()),
                ('bytes_received', models.BigIntegerField()),
                ('current_users', models.IntegerField()),
                ('logged_in_users', models.TextField()),
            ],
        ),
    ]
