# Generated by Django 5.1.7 on 2026-02-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(db_index=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('os_name', models.CharField(blank=True, max_length=100, null=True)),
                ('os_version', models.CharField(blank=True, max_length=100, null=True)),
                ('cpu_usage', models.FloatField(blank=True, help_text='Percentage 0-100', null=True)),
                ('ram_usage', models.FloatField(blank=True, help_text='Percentage 0-100', null=True)),
                ('disk_usage', models.FloatField(blank=True, help_text='Percentage 0-100', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
                'indexes': [models.Index(fields=['hostname', '-timestamp'], name='monitoring__hostnam_2b20b1_idx')],
            },
        ),
    ]
