# Generated by Django 5.1.7 on 2025-04-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systeminfo',
            old_name='available_memory',
            new_name='cpu_current_freq',
        ),
        migrations.RenameField(
            model_name='systeminfo',
            old_name='current_frequency',
            new_name='cpu_max_freq',
        ),
        migrations.RenameField(
            model_name='systeminfo',
            old_name='disk_usage',
            new_name='cpu_min_freq',
        ),
        migrations.RenameField(
            model_name='systeminfo',
            old_name='physical_cores',
            new_name='cpu_physical_cores',
        ),
        migrations.RenameField(
            model_name='systeminfo',
            old_name='total_cores',
            new_name='cpu_total_cores',
        ),
        migrations.RenameField(
            model_name='systeminfo',
            old_name='free_disk_space',
            new_name='disk_free',
        ),
        migrations.RenameField(
            model_name='systeminfo',
            old_name='max_frequency',
            new_name='disk_total',
        ),
        migrations.RenameField(
            model_name='systeminfo',
            old_name='memory_usage',
            new_name='disk_usage_percent',
        ),
        migrations.RenameField(
            model_name='systeminfo',
            old_name='min_frequency',
            new_name='disk_used',
        ),
        migrations.RenameField(
            model_name='systeminfo',
            old_name='total_disk_space',
            new_name='memory_available',
        ),
        migrations.RenameField(
            model_name='systeminfo',
            old_name='total_memory',
            new_name='memory_total',
        ),
        migrations.RenameField(
            model_name='systeminfo',
            old_name='used_disk_space',
            new_name='memory_usage_percent',
        ),
        migrations.RenameField(
            model_name='systeminfo',
            old_name='used_memory',
            new_name='memory_used',
        ),
        migrations.RemoveField(
            model_name='systeminfo',
            name='mac_address',
        ),
        migrations.AlterField(
            model_name='systeminfo',
            name='architecture',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='systeminfo',
            name='logged_in_users',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='systeminfo',
            name='machine',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='systeminfo',
            name='system',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='systeminfo',
            name='version',
            field=models.CharField(max_length=100),
        ),
    ]
