# Generated by Django 5.1.7 on 2025-04-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_rename_available_memory_systeminfo_cpu_current_freq_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systeminfo',
            old_name='current_users',
            new_name='users_count',
        ),
        migrations.AlterField(
            model_name='systeminfo',
            name='architecture',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='systeminfo',
            name='logged_in_users',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='systeminfo',
            name='machine',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='systeminfo',
            name='release',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='systeminfo',
            name='system',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='systeminfo',
            name='version',
            field=models.TextField(),
        ),
    ]
