# Generated by Django 5.1.7 on 2026-07-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_systeminfo_add_extended_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='systeminfo',
            name='boot_time',
            field=models.FloatField(blank=True, help_text='Unix timestamp of last system boot', null=True),
        ),
        migrations.AddField(
            model_name='systeminfo',
            name='uptime_seconds',
            field=models.FloatField(blank=True, help_text='Seconds since last boot at snapshot time', null=True),
        ),
    ]
