# Generated by Django 5.2.3 on 2026-07-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_add_uptime_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='systeminfo',
            name='today_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='systeminfo',
            name='today_uptime_formatted',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='systeminfo',
            name='today_uptime_seconds',
            field=models.FloatField(blank=True, help_text='Total seconds the PC has been ON today', null=True),
        ),
    ]
