from rest_framework import serializers
#this file is for rest framework
class SystemInfoSerializer(serializers.Serializer):
    hostname = serializers.CharField()
    system = serializers.CharField()
    version = serializers.CharField()
    release = serializers.CharField()
    machine = serializers.CharField()
    processor = serializers.CharField()
    architecture = serializers.CharField()
    cpu_physical_cores = serializers.IntegerField()
    cpu_total_cores = serializers.IntegerField()
    cpu_max_freq = serializers.FloatField()
    cpu_min_freq = serializers.FloatField()
    cpu_current_freq = serializers.FloatField()
    cpu_usage = serializers.FloatField()
    total_memory = serializers.FloatField()
    available_memory = serializers.FloatField()
    used_memory = serializers.FloatField()
    memory_usage = serializers.FloatField()
    total_disk = serializers.FloatField()
    used_disk = serializers.FloatField()
    free_disk = serializers.FloatField()
    disk_usage = serializers.FloatField()
    ip_address = serializers.CharField()
    bytes_sent = serializers.IntegerField()
    bytes_received = serializers.IntegerField()
    current_users = serializers.IntegerField()
    logged_in_users = serializers.ListField(child=serializers.CharField())
