# Generated by Django 5.1.7 on 2025-04-08 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system_layout', '0002_remove_lab_instructor_lab_assistants_lab_instructors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceRequest',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('Hardware', 'Hardware'), ('Software', 'Software'), ('Network', 'Network')], db_index=True, max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_index=True, max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('provided_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('system_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_layout.layoutitem')),
            ],
        ),
    ]
