# Generated by Django 5.2.3 on 2025-07-06 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system_layout', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceRequest',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('resource_name', models.TextField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Fulfilled', 'Fulfilled'), ('Denied', 'Denied')], default='Pending', max_length=30)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('system_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_layout.system')),
            ],
        ),
        migrations.CreateModel(
            name='Provided',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provision_summary', models.TextField()),
                ('provided_at', models.DateTimeField(auto_now_add=True)),
                ('provided_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resource_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resources.resourcerequest')),
            ],
        ),
    ]
