# Generated by Django 5.2.3 on 2025-07-02 17:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcerequest',
            name='resource_type',
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='resource_name',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
