# Generated by Django 6.0.5 on 2026-07-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_inline_provided_into_resourcerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcerequest',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
