# Generated by Django 5.1.7 on 2025-03-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Lab Incharge', 'Lab Incharge'), ('Lab Assistant', 'Lab Assistant'), ('Student', 'Student'), ('No Roles', 'No Roles')], db_column='role', db_index=True, default='No Roles', max_length=20),
        ),
    ]
