# Generated by Django 5.1.7 on 2025-03-31 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_manager', '0002_alter_user_options_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Lab Incharge', 'Lab Incharge'), ('Lab Assistant', 'Lab Assistant'), ('Students', 'Students'), ('No Roles', 'No Roles')], db_column='role', db_index=True, default='No Roles', max_length=20),
        ),
    ]
