# Generated by Django 5.1.7 on 2025-06-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_manager', '0003_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Lab Incharge', 'Lab Incharge'), ('Lab Assistant', 'Lab Assistant'), ('Students', 'Students'), ('No Roles', 'No Roles')], db_index=True, default='No Roles', max_length=20),
        ),
    ]
