# Generated by Django 5.1.7 on 2026-03-08 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_notification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='api_v1_noti_recipie_653b7c_idx',
            old_name='api_v1_noti_recipie_b5ef40_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='api_v1_noti_related_a4489f_idx',
            old_name='api_v1_noti_related_30fb3a_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='api_v1_noti_created_576abd_idx',
            old_name='api_v1_noti_created_e46fba_idx',
        ),
    ]
