# Generated by Django 5.2.3 on 2025-07-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaultReport',
            fields=[
                ('fault_id', models.AutoField(primary_key=True, serialize=False)),
                ('fault_type', models.CharField(choices=[('Hardware', 'Hardware'), ('Software', 'Software'), ('Network', 'Network')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('unaddressed', 'Unaddressed'), ('in-progress', 'In Progress'), ('scheduled', 'Scheduled'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='unaddressed', max_length=30)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='Resolved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution_summary', models.TextField()),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
