# Generated by Django 5.2.3 on 2025-06-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaultReport',
            fields=[
                ('fault_id', models.AutoField(db_column='fault_id', primary_key=True, serialize=False)),
                ('fault_type', models.CharField(choices=[('Hardware', 'Hardware'), ('Software', 'Software'), ('Network', 'Network')], db_column='fault_type', max_length=20)),
                ('description', models.TextField(db_column='description')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], db_column='status', max_length=30)),
                ('reported_at', models.DateTimeField(auto_now_add=True, db_column='reported_at')),
                ('resolved_at', models.DateTimeField(blank=True, db_column='resolved_at', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resolved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution_summary', models.TextField(db_column='resolution_summary')),
                ('resolved_at', models.DateTimeField(auto_now_add=True, db_column='resolved_at')),
                ('further_action_required', models.BooleanField(db_column='further_action_required', default=False)),
            ],
        ),
    ]
