# Generated by Django 5.1.7 on 2026-02-24 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system_layout', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaultReport',
            fields=[
                ('fault_id', models.AutoField(primary_key=True, serialize=False)),
                ('fault_type', models.CharField(choices=[('Hardware', 'Hardware'), ('Software', 'Software'), ('Network', 'Network')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('unaddressed', 'Unaddressed'), ('in-progress', 'In Progress'), ('scheduled', 'Scheduled'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='unaddressed', max_length=30)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('system_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_layout.system')),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='Resolved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution_summary', models.TextField()),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
                ('fault_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='faults.faultreport')),
                ('resolved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='faultreport',
            index=models.Index(fields=['status'], name='faults_faul_status_a7915e_idx'),
        ),
        migrations.AddIndex(
            model_name='faultreport',
            index=models.Index(fields=['reported_at'], name='faults_faul_reporte_9634de_idx'),
        ),
        migrations.AddIndex(
            model_name='faultreport',
            index=models.Index(fields=['system_name'], name='faults_faul_system__ad09af_idx'),
        ),
    ]
