# Generated by Django 5.2.3 on 2025-07-01 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faults', '0001_initial'),
        ('system_layout', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='faultreport',
            name='reported_by',
            field=models.ForeignKey(db_column='reported_by_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faultreport',
            name='system_name',
            field=models.ForeignKey(db_column='system_name_id', on_delete=django.db.models.deletion.CASCADE, to='system_layout.layoutitem'),
        ),
        migrations.AddField(
            model_name='resolved',
            name='fault_report',
            field=models.ForeignKey(db_column='fault_report_id', on_delete=django.db.models.deletion.CASCADE, to='faults.faultreport'),
        ),
        migrations.AddField(
            model_name='resolved',
            name='resolved_by',
            field=models.ForeignKey(db_column='resolved_by_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
