# Generated by Django 5.2.3 on 2025-07-06 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faults', '0001_initial'),
        ('system_layout', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='faultreport',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faultreport',
            name='system_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_layout.system'),
        ),
        migrations.AddField(
            model_name='resolved',
            name='fault_report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='faults.faultreport'),
        ),
        migrations.AddField(
            model_name='resolved',
            name='resolved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='faultreport',
            index=models.Index(fields=['status'], name='faults_faul_status_a7915e_idx'),
        ),
        migrations.AddIndex(
            model_name='faultreport',
            index=models.Index(fields=['reported_at'], name='faults_faul_reporte_9634de_idx'),
        ),
        migrations.AddIndex(
            model_name='faultreport',
            index=models.Index(fields=['system_name'], name='faults_faul_system__ad09af_idx'),
        ),
    ]
