# Generated by Django 5.1.7 on 2025-04-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faultreport',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], db_column='status', max_length=30),
        ),
    ]
