# Generated by Django 5.2.3 on 2025-07-01 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resolved',
            name='further_action_required',
        ),
    ]
