# Generated by Django 5.2.3 on 2025-07-01 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0003_remove_resolved_further_action_required'),
        ('system_layout', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faultreport',
            options={'ordering': ['-reported_at']},
        ),
        migrations.AlterField(
            model_name='faultreport',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='faultreport',
            name='fault_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='faultreport',
            name='fault_type',
            field=models.CharField(choices=[('Hardware', 'Hardware'), ('Software', 'Software'), ('Network', 'Network')], max_length=20),
        ),
        migrations.AlterField(
            model_name='faultreport',
            name='reported_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='faultreport',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='faultreport',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faultreport',
            name='status',
            field=models.CharField(choices=[('unaddressed', 'Unaddressed'), ('in-progress', 'In Progress'), ('scheduled', 'Scheduled'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='unaddressed', max_length=30),
        ),
        migrations.AlterField(
            model_name='faultreport',
            name='system_name',
            field=models.ForeignKey(limit_choices_to={'item_type': 'system'}, on_delete=django.db.models.deletion.CASCADE, to='system_layout.layoutitem'),
        ),
        migrations.AlterField(
            model_name='resolved',
            name='fault_report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='faults.faultreport'),
        ),
        migrations.AlterField(
            model_name='resolved',
            name='resolution_summary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resolved',
            name='resolved_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='resolved',
            name='resolved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='faultreport',
            index=models.Index(fields=['status'], name='faults_faul_status_a7915e_idx'),
        ),
        migrations.AddIndex(
            model_name='faultreport',
            index=models.Index(fields=['reported_at'], name='faults_faul_reporte_9634de_idx'),
        ),
        migrations.AddIndex(
            model_name='faultreport',
            index=models.Index(fields=['system_name'], name='faults_faul_system__ad09af_idx'),
        ),
    ]
