# Generated by Django 5.2.3 on 2025-07-02 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0004_alter_faultreport_options_and_more'),
        ('system_layout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faultreport',
            name='resolved_at',
        ),
        migrations.AlterField(
            model_name='faultreport',
            name='system_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_layout.system'),
        ),
    ]
