# Generated by Django 5.2.3 on 2025-07-01 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('item_type', models.CharField(choices=[('building', 'Building'), ('floor', 'Floor'), ('room', 'Room'), ('computer', 'Computer'), ('server', 'Server'), ('network_switch', 'Network Switch'), ('router', 'Router'), ('printer', 'Printer'), ('ups', 'UPS'), ('rack', 'Server Rack')], db_index=True, max_length=20)),
                ('position_x', models.PositiveIntegerField(default=0)),
                ('position_y', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=1)),
                ('height', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='system_layout.layoutitem')),
            ],
            options={
                'ordering': ['item_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('capacity', models.IntegerField(null=True)),
                ('dimension', models.CharField(max_length=50, null=True)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('layout_item', models.OneToOneField(blank=True, limit_choices_to={'item_type': 'room'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab', to='system_layout.layoutitem')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.TextField(blank=True, default='', null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active (System is turned on)'), ('inactive', 'Inactive (Turned off but functional)'), ('non-functional', 'Non-Functional (Needs repair or replacement)')], default='active', max_length=20, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_layout.lab')),
                ('layout_item', models.OneToOneField(limit_choices_to={'item_type__in': ['computer', 'server', 'network_switch', 'router', 'printer', 'ups', 'rack']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system', to='system_layout.layoutitem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
