# Generated by Django 5.1.7 on 2026-02-24 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_layout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_children', to='system_layout.layoutitem'),
        ),
        migrations.AlterField(
            model_name='system',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system_layout.lab'),
        ),
    ]
