# Generated by Django 5.1.7 on 2025-03-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_layout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layoutitem',
            name='height',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='layoutitem',
            name='item_type',
            field=models.CharField(choices=[('building', 'Building'), ('floor', 'Floor'), ('room', 'Room'), ('computer', 'Computer'), ('server', 'Server'), ('network_switch', 'Network Switch'), ('router', 'Router'), ('printer', 'Printer'), ('ups', 'UPS'), ('rack', 'Server Rack')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='layoutitem',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='layoutitem',
            name='position_x',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='layoutitem',
            name='position_y',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='layoutitem',
            name='width',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
