# Generated by Django 5.2.3 on 2025-07-07 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_layout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='parent',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='lab_children', to='system_layout.layoutitem'),
            preserve_default=False,
        ),
    ]
