# Generated by Django 5.1.7 on 2025-04-07 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_layout', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='instructor',
        ),
        migrations.AddField(
            model_name='lab',
            name='assistants',
            field=models.ManyToManyField(blank=True, related_name='assisted_labs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lab',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='instructed_labs', to=settings.AUTH_USER_MODEL),
        ),
    ]
