# Generated by Django 5.1.7 on 2025-03-09 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_layout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('building', 'Building'), ('floor', 'Floor'), ('room', 'Room'), ('computer', 'Computer'), ('server', 'Server'), ('network_switch', 'Network Switch'), ('router', 'Router'), ('printer', 'Printer'), ('ups', 'UPS'), ('rack', 'Server Rack')], max_length=20)),
                ('x_position', models.IntegerField(default=0)),
                ('y_position', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='system_layout.layoutitem')),
            ],
        ),
    ]
