# Generated by Django 5.1.7 on 2025-04-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_layout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='dimension',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
