# Generated by Django 5.1.7 on 2025-04-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_layout', '0002_alter_lab_capacity_alter_lab_dimension_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='updated_by',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
