# Generated by Django 5.2.3 on 2025-07-07 04:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_layout', '0002_alter_lab_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='assistants',
            field=models.ManyToManyField(null=True, related_name='assistant_labs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lab',
            name='instructors',
            field=models.ManyToManyField(null=True, related_name='instructor_labs', to=settings.AUTH_USER_MODEL),
        ),
    ]
