# Generated by Django 5.1.7 on 2026-02-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_layout', '0002_alter_lab_parent_alter_system_lab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='quick_info',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='host_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
