# Generated by Django 5.1.7 on 2025-03-09 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_layout', '0002_layoutitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Block',
        ),
    ]
