# Generated by Django 5.1.7 on 2026-02-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_layout', '0003_alter_lab_quick_info_alter_system_host_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='lab_code',
            field=models.CharField(blank=True, db_index=True, help_text='Short unique code used for QR identification, e.g. LAB-A101', max_length=20, null=True, unique=True),
        ),
    ]
