# Generated by Django 5.1.7 on 2025-04-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_layout', '0003_alter_system_updated_at_alter_system_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='status',
            field=models.CharField(choices=[('active', 'Active (System is turned on)'), ('inactive', 'Inactive (Turned off but functional)'), ('non-functional', 'Non-Functional (Needs repair or replacement)')], default='inactive', max_length=20, null=True),
        ),
    ]
