# Generated by Django 5.1.7 on 2025-03-11 14:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('system_layout', '0003_delete_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=100)),
                ('cpu', models.CharField(blank=True, max_length=100)),
                ('ram', models.CharField(blank=True, max_length=50)),
                ('storage', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkDeviceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('ports', models.IntegerField(default=0)),
                ('manageable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ServerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('cpu', models.CharField(blank=True, max_length=100)),
                ('ram', models.CharField(blank=True, max_length=50)),
                ('storage', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='layoutitem',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='layoutitem',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='layoutitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layoutitem',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='layoutitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AddField(
            model_name='layoutitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='layoutitem',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='layoutitem',
            name='item_type',
            field=models.CharField(choices=[('building', 'Building'), ('floor', 'Floor'), ('room', 'Room'), ('computer', 'Computer'), ('server', 'Server'), ('network_switch', 'Network Switch'), ('router', 'Router'), ('printer', 'Printer'), ('ups', 'UPS'), ('rack', 'Server Rack')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='layoutitem',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='layoutitem',
            index=models.Index(fields=['parent', 'item_type'], name='system_layo_parent__449fe5_idx'),
        ),
        migrations.AddIndex(
            model_name='layoutitem',
            index=models.Index(fields=['item_type', 'name'], name='system_layo_item_ty_a555fd_idx'),
        ),
    ]
