# Generated by Django 5.2.3 on 2025-07-07 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_layout', '0003_alter_lab_assistants_alter_lab_instructors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='assistants',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='instructors',
        ),
    ]
