# Generated by Django 5.1.7 on 2025-04-05 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_layout', '0004_alter_system_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='layout_item',
            field=models.OneToOneField(limit_choices_to={'item_type': 'computer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system', to='system_layout.layoutitem'),
        ),
    ]
