# Generated by Django 5.2.3 on 2025-07-07 04:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_layout', '0004_remove_lab_assistants_remove_lab_instructors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='assistants',
            field=models.ManyToManyField(blank=True, related_name='assistant_labs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lab',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='instructor_labs', to=settings.AUTH_USER_MODEL),
        ),
    ]
