# Generated by Django 5.1.7 on 2026-02-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_layout', '0005_remove_lab_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layoutitem',
            name='position_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='layoutitem',
            name='position_y',
            field=models.IntegerField(default=0),
        ),
    ]
