# Generated by Django 5.2.3 on 2025-07-07 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_layout', '0005_lab_assistants_lab_instructors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='layout_item',
            field=models.OneToOneField(default=1, limit_choices_to={'item_type': 'room'}, on_delete=django.db.models.deletion.CASCADE, related_name='lab', to='system_layout.layoutitem'),
            preserve_default=False,
        ),
    ]
