# Generated by Django 5.2.3 on 2025-07-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_layout', '0006_alter_lab_layout_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='quick_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
