# Generated by Django 6.0.5 on 2026-07-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_layout', '0007_labassignment_privilegesconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='privilegesconfig',
            name='max_assistants_per_lab',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of concurrently active Lab Assistants per lab.'),
        ),
        migrations.AddField(
            model_name='privilegesconfig',
            name='max_incharges_per_lab',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of concurrently active Lab Incharges per lab.'),
        ),
    ]
