# Generated by Django 5.1.7 on 2026-07-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_layout', '0008_privilegesconfig_max_assistants_per_lab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active (System is turned on)'), ('inactive', 'Inactive (Turned off but functional)'), ('non-functional', 'Non-Functional (Needs repair or replacement)')], default='inactive', max_length=20, null=True),
        ),
    ]
