# Generated by Django 5.1.7 on 2026-08-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_layout', '0009_change_system_status_default_to_inactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heartbeat_interval_minutes', models.PositiveIntegerField(default=5, help_text='How often (in minutes) each system sends a heartbeat ping.')),
                ('offline_detection_threshold_minutes', models.PositiveIntegerField(default=15, help_text='If no heartbeat is received for this many minutes, the system is considered offline.')),
                ('max_log_retention_days', models.PositiveIntegerField(default=90, help_text='Automatic purge threshold for monitoring logs older than this many days.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Monitoring Configuration',
            },
        ),
    ]
