# Generated by Django 5.2.3 on 2025-07-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabAssignmentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_limit', models.PositiveIntegerField(default=3)),
                ('assistant_limit', models.PositiveIntegerField(default=5)),
                ('lab_capacity_limit', models.PositiveIntegerField(default=30)),
                ('lab_dimension_limit', models.CharField(default='10x10', max_length=50)),
            ],
        ),
    ]
