# Generated by Django 5.1.7 on 2026-02-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabAssignmentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_limit', models.PositiveIntegerField(default=5)),
                ('assistant_limit', models.PositiveIntegerField(default=5)),
            ],
            options={
                'verbose_name': 'Lab Limits',
                'verbose_name_plural': 'Lab Limits',
            },
        ),
    ]
