# Generated by Django 5.2.3 on 2025-07-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprivileges', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labassignmentsetting',
            options={'verbose_name': 'Lab Limits', 'verbose_name_plural': 'Lab Limits'},
        ),
    ]
