# Generated by Django 5.2.3 on 2025-07-07 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprivileges', '0002_alter_labassignmentsetting_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labassignmentsetting',
            name='lab_capacity_limit',
        ),
        migrations.RemoveField(
            model_name='labassignmentsetting',
            name='lab_dimension_limit',
        ),
    ]
