# Generated by Django 5.2.3 on 2025-07-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprivileges', '0003_remove_labassignmentsetting_lab_capacity_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labassignmentsetting',
            name='instructor_limit',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
