# Generated by Django 5.1.7 on 2026-03-08 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('action', models.CharField(db_index=True, max_length=120)),
                ('actor_user_id', models.IntegerField(blank=True, null=True)),
                ('actor_username', models.CharField(blank=True, max_length=150)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('source', models.CharField(default='system', max_length=50)),
                ('object_type', models.CharField(blank=True, max_length=80)),
                ('object_id', models.CharField(blank=True, max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='tenant_control.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='tenant_cont_tenant__401914_idx'), models.Index(fields=['category', 'created_at'], name='tenant_cont_categor_342612_idx'), models.Index(fields=['action', 'created_at'], name='tenant_cont_action_a27814_idx')],
            },
        ),
    ]
